name: Publish release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            outfile: bunsync
          - os: windows-latest
            outfile: bunsync.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun build ./bunsync.js --compile --outfile ${{ matrix.outfile }}
      - uses: actions/upload-artifact@v4
        with:
          name: bunsync-${{ matrix.os }}
          path: ${{ matrix.outfile }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Create pre-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bunsync-ubuntu-latest/bunsync
            bunsync-windows-latest/bunsync.exe
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
